import type { Metadata } from "next";
import "./globals.css";
import { GSAP } from "@/app/components/globals/gsap/gsap";
export const metadata: Metadata = {
  title: "UB7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* GSAP */}
        <GSAP scrollTrigger={true} />
      </body>
    </html>
  );
}
